version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  criptografia:
    container_name: criptografia
    build: ./criptografia
    volumes:
      - ./criptografia:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: null
